/**
 * Quatrix API
 * The Quatrix API enables you to automate your interaction with Quatrix using any scripting or programming language. You can test API calls on [Swagger](https://docs.maytech.net/swagger/), the interactive environment we use as the repository for the Quatrix API. In order to authorize to Quatrix API you will need to have a Quatrix account https://yourcompanyname.quatrix.it/ (e.g. https://test-api.quatrix.it/). You can set up a free trial account [here](https://www.maytech.net/freetrial.html#trial=qtrx). Below you'll find information on how to authenticate in a Quatrix session, how to construct JSON formatted API call and what JSON responses to expect.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AutomationOptions'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AutomationOptions'));
  } else {
    // Browser globals (root is window)
    if (!root.QuatrixApi) {
      root.QuatrixApi = {};
    }
    root.QuatrixApi.AutomationCreateReq = factory(root.QuatrixApi.ApiClient, root.QuatrixApi.AutomationOptions);
  }
}(this, function(ApiClient, AutomationOptions) {
  'use strict';




  /**
   * The AutomationCreateReq model module.
   * @module model/AutomationCreateReq
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AutomationCreateReq</code>.
   * @alias module:model/AutomationCreateReq
   * @class
   * @param fileId {String} 
   * @param action {module:model/AutomationCreateReq.ActionEnum} 
   */
  var exports = function(fileId, action) {
    var _this = this;

    _this['file_id'] = fileId;
    _this['action'] = action;





  };

  /**
   * Constructs a <code>AutomationCreateReq</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AutomationCreateReq} obj Optional instance to populate.
   * @return {module:model/AutomationCreateReq} The populated <code>AutomationCreateReq</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('file_id')) {
        obj['file_id'] = ApiClient.convertToType(data['file_id'], 'String');
      }
      if (data.hasOwnProperty('action')) {
        obj['action'] = ApiClient.convertToType(data['action'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('options')) {
        obj['options'] = AutomationOptions.constructFromObject(data['options']);
      }
      if (data.hasOwnProperty('comment')) {
        obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
      }
      if (data.hasOwnProperty('expires')) {
        obj['expires'] = ApiClient.convertToType(data['expires'], 'Number');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {String} file_id
   */
  exports.prototype['file_id'] = undefined;
  /**
   * @member {module:model/AutomationCreateReq.ActionEnum} action
   */
  exports.prototype['action'] = undefined;
  /**
   * @member {module:model/AutomationCreateReq.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {module:model/AutomationOptions} options
   */
  exports.prototype['options'] = undefined;
  /**
   * @member {String} comment
   */
  exports.prototype['comment'] = undefined;
  /**
   * @member {Number} expires
   */
  exports.prototype['expires'] = undefined;
  /**
   * @member {Array.<String>} email
   */
  exports.prototype['email'] = undefined;


  /**
   * Allowed values for the <code>action</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ActionEnum = {
    /**
     * value: "autodelete"
     * @const
     */
    "autodelete": "autodelete",
    /**
     * value: "video_upload"
     * @const
     */
    "video_upload": "video_upload"  };

  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "A"
     * @const
     */
    "A": "A",
    /**
     * value: "D"
     * @const
     */
    "D": "D"  };


  return exports;
}));


