/**
 * Quatrix API
 * The Quatrix API enables you to automate your interaction with Quatrix using any scripting or programming language. You can test API calls on [Swagger](https://docs.maytech.net/swagger/), the interactive environment we use as the repository for the Quatrix API. In order to authorize to Quatrix API you will need to have a Quatrix account https://yourcompanyname.quatrix.it/ (e.g. https://test-api.quatrix.it/). You can set up a free trial account [here](https://www.maytech.net/freetrial.html#trial=qtrx). Below you'll find information on how to authenticate in a Quatrix session, how to construct JSON formatted API call and what JSON responses to expect.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.QuatrixApi) {
      root.QuatrixApi = {};
    }
    root.QuatrixApi.AutomationOptions = factory(root.QuatrixApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AutomationOptions model module.
   * @module model/AutomationOptions
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AutomationOptions</code>.
   * automation metadata json
   * @alias module:model/AutomationOptions
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>AutomationOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AutomationOptions} obj Optional instance to populate.
   * @return {module:model/AutomationOptions} The populated <code>AutomationOptions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('expire')) {
        obj['expire'] = ApiClient.convertToType(data['expire'], 'Number');
      }
      if (data.hasOwnProperty('keep_folder_structure')) {
        obj['keep_folder_structure'] = ApiClient.convertToType(data['keep_folder_structure'], 'Boolean');
      }
      if (data.hasOwnProperty('protected_folder_ids')) {
        obj['protected_folder_ids'] = ApiClient.convertToType(data['protected_folder_ids'], ['String']);
      }
      if (data.hasOwnProperty('skip_home_folders')) {
        obj['skip_home_folders'] = ApiClient.convertToType(data['skip_home_folders'], 'Boolean');
      }
      if (data.hasOwnProperty('skip_shared_folders')) {
        obj['skip_shared_folders'] = ApiClient.convertToType(data['skip_shared_folders'], 'Boolean');
      }
      if (data.hasOwnProperty('super_trash')) {
        obj['super_trash'] = ApiClient.convertToType(data['super_trash'], 'Boolean');
      }
      if (data.hasOwnProperty('oauth_code')) {
        obj['oauth_code'] = ApiClient.convertToType(data['oauth_code'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} expire
   */
  exports.prototype['expire'] = undefined;
  /**
   * @member {Boolean} keep_folder_structure
   */
  exports.prototype['keep_folder_structure'] = undefined;
  /**
   * @member {Array.<String>} protected_folder_ids
   */
  exports.prototype['protected_folder_ids'] = undefined;
  /**
   * @member {Boolean} skip_home_folders
   */
  exports.prototype['skip_home_folders'] = undefined;
  /**
   * @member {Boolean} skip_shared_folders
   */
  exports.prototype['skip_shared_folders'] = undefined;
  /**
   * @member {Boolean} super_trash
   */
  exports.prototype['super_trash'] = undefined;
  /**
   * @member {String} oauth_code
   */
  exports.prototype['oauth_code'] = undefined;



  return exports;
}));


