/**
 * Quatrix API
 * The Quatrix API enables you to automate your interaction with Quatrix using any scripting or programming language. You can test API calls on [Swagger](https://docs.maytech.net/swagger/), the interactive environment we use as the repository for the Quatrix API. In order to authorize to Quatrix API you will need to have a Quatrix account https://yourcompanyname.quatrix.it/ (e.g. https://test-api.quatrix.it/). You can set up a free trial account [here](https://www.maytech.net/freetrial.html#trial=qtrx). Below you'll find information on how to authenticate in a Quatrix session, how to construct JSON formatted API call and what JSON responses to expect.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.QuatrixApi) {
      root.QuatrixApi = {};
    }
    root.QuatrixApi.CopyMoveFilesReq = factory(root.QuatrixApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CopyMoveFilesReq model module.
   * @module model/CopyMoveFilesReq
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CopyMoveFilesReq</code>.
   * @alias module:model/CopyMoveFilesReq
   * @class
   * @param ids {Array.<String>} 
   * @param target {String} 
   */
  var exports = function(ids, target) {
    var _this = this;

    _this['ids'] = ids;
    _this['target'] = target;

  };

  /**
   * Constructs a <code>CopyMoveFilesReq</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CopyMoveFilesReq} obj Optional instance to populate.
   * @return {module:model/CopyMoveFilesReq} The populated <code>CopyMoveFilesReq</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ids')) {
        obj['ids'] = ApiClient.convertToType(data['ids'], ['String']);
      }
      if (data.hasOwnProperty('target')) {
        obj['target'] = ApiClient.convertToType(data['target'], 'String');
      }
      if (data.hasOwnProperty('resolve')) {
        obj['resolve'] = ApiClient.convertToType(data['resolve'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<String>} ids
   */
  exports.prototype['ids'] = undefined;
  /**
   * @member {String} target
   */
  exports.prototype['target'] = undefined;
  /**
   * @member {Boolean} resolve
   * @default true
   */
  exports.prototype['resolve'] = true;



  return exports;
}));


