/**
 * Quatrix API
 * The Quatrix API enables you to automate your interaction with Quatrix using any scripting or programming language. You can test API calls on [Swagger](https://docs.maytech.net/swagger/), the interactive environment we use as the repository for the Quatrix API. In order to authorize to Quatrix API you will need to have a Quatrix account https://yourcompanyname.quatrix.it/ (e.g. https://test-api.quatrix.it/). You can set up a free trial account [here](https://www.maytech.net/freetrial.html#trial=qtrx). Below you'll find information on how to authenticate in a Quatrix session, how to construct JSON formatted API call and what JSON responses to expect.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.QuatrixApi) {
      root.QuatrixApi = {};
    }
    root.QuatrixApi.FileInfoResp = factory(root.QuatrixApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FileInfoResp model module.
   * @module model/FileInfoResp
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>FileInfoResp</code>.
   * @alias module:model/FileInfoResp
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>FileInfoResp</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FileInfoResp} obj Optional instance to populate.
   * @return {module:model/FileInfoResp} The populated <code>FileInfoResp</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('created')) {
        obj['created'] = ApiClient.convertToType(data['created'], 'Number');
      }
      if (data.hasOwnProperty('modified')) {
        obj['modified'] = ApiClient.convertToType(data['modified'], 'Number');
      }
      if (data.hasOwnProperty('content_modified')) {
        obj['content_modified'] = ApiClient.convertToType(data['content_modified'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('size')) {
        obj['size'] = ApiClient.convertToType(data['size'], 'Number');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('file_owner')) {
        obj['file_owner'] = ApiClient.convertToType(data['file_owner'], Object);
      }
      if (data.hasOwnProperty('action_role')) {
        obj['action_role'] = ApiClient.convertToType(data['action_role'], Object);
      }
      if (data.hasOwnProperty('paths')) {
        obj['paths'] = ApiClient.convertToType(data['paths'], Object);
      }
    }
    return obj;
  }

  /**
   * File ID
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * File creation timestamp
   * @member {Number} created
   */
  exports.prototype['created'] = undefined;
  /**
   * File modification timestamp
   * @member {Number} modified
   */
  exports.prototype['modified'] = undefined;
  /**
   * File content modification timestamp
   * @member {Number} content_modified
   */
  exports.prototype['content_modified'] = undefined;
  /**
   * File name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * File size in bytes
   * @member {Number} size
   */
  exports.prototype['size'] = undefined;
  /**
   * File type
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * Owner of Folder/File
   * @member {Object} file_owner
   */
  exports.prototype['file_owner'] = undefined;
  /**
   * Role that created/uploaded Folder/File
   * @member {Object} action_role
   */
  exports.prototype['action_role'] = undefined;
  /**
   * Path and Type of path to File
   * @member {Object} paths
   */
  exports.prototype['paths'] = undefined;



  return exports;
}));


