/**
 * Quatrix API
 * The Quatrix API enables you to automate your interaction with Quatrix using any scripting or programming language. You can test API calls on [Swagger](https://docs.maytech.net/swagger/), the interactive environment we use as the repository for the Quatrix API. In order to authorize to Quatrix API you will need to have a Quatrix account https://yourcompanyname.quatrix.it/ (e.g. https://test-api.quatrix.it/). You can set up a free trial account [here](https://www.maytech.net/freetrial.html#trial=qtrx). Below you'll find information on how to authenticate in a Quatrix session, how to construct JSON formatted API call and what JSON responses to expect.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UserPermissionReq'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UserPermissionReq'));
  } else {
    // Browser globals (root is window)
    if (!root.QuatrixApi) {
      root.QuatrixApi = {};
    }
    root.QuatrixApi.PfaddUsersReq = factory(root.QuatrixApi.ApiClient, root.QuatrixApi.UserPermissionReq);
  }
}(this, function(ApiClient, UserPermissionReq) {
  'use strict';




  /**
   * The PfaddUsersReq model module.
   * @module model/PfaddUsersReq
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PfaddUsersReq</code>.
   * @alias module:model/PfaddUsersReq
   * @class
   * @param usersPermissions {Array.<module:model/UserPermissionReq>} 
   */
  var exports = function(usersPermissions) {
    var _this = this;

    _this['users_permissions'] = usersPermissions;
  };

  /**
   * Constructs a <code>PfaddUsersReq</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PfaddUsersReq} obj Optional instance to populate.
   * @return {module:model/PfaddUsersReq} The populated <code>PfaddUsersReq</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('users_permissions')) {
        obj['users_permissions'] = ApiClient.convertToType(data['users_permissions'], [UserPermissionReq]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/UserPermissionReq>} users_permissions
   */
  exports.prototype['users_permissions'] = undefined;



  return exports;
}));


