/**
 * Quatrix API
 * The Quatrix API enables you to automate your interaction with Quatrix using any scripting or programming language. You can test API calls on [Swagger](https://docs.maytech.net/swagger/), the interactive environment we use as the repository for the Quatrix API. In order to authorize to Quatrix API you will need to have a Quatrix account https://yourcompanyname.quatrix.it/ (e.g. https://test-api.quatrix.it/). You can set up a free trial account [here](https://www.maytech.net/freetrial.html#trial=qtrx). Below you'll find information on how to authenticate in a Quatrix session, how to construct JSON formatted API call and what JSON responses to expect.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.QuatrixApi) {
      root.QuatrixApi = {};
    }
    root.QuatrixApi.ProfileRespShareTypes = factory(root.QuatrixApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ProfileRespShareTypes model module.
   * @module model/ProfileRespShareTypes
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ProfileRespShareTypes</code>.
   * @alias module:model/ProfileRespShareTypes
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ProfileRespShareTypes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProfileRespShareTypes} obj Optional instance to populate.
   * @return {module:model/ProfileRespShareTypes} The populated <code>ProfileRespShareTypes</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('restricted_share')) {
        obj['restricted_share'] = ApiClient.convertToType(data['restricted_share'], 'Boolean');
      }
      if (data.hasOwnProperty('public_share')) {
        obj['public_share'] = ApiClient.convertToType(data['public_share'], 'Boolean');
      }
      if (data.hasOwnProperty('tracked_share')) {
        obj['tracked_share'] = ApiClient.convertToType(data['tracked_share'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} restricted_share
   */
  exports.prototype['restricted_share'] = undefined;
  /**
   * @member {Boolean} public_share
   */
  exports.prototype['public_share'] = undefined;
  /**
   * @member {Boolean} tracked_share
   */
  exports.prototype['tracked_share'] = undefined;



  return exports;
}));


