/**
 * Quatrix API
 * The Quatrix API enables you to automate your interaction with Quatrix using any scripting or programming language. You can test API calls on [Swagger](https://docs.maytech.net/swagger/), the interactive environment we use as the repository for the Quatrix API. In order to authorize to Quatrix API you will need to have a Quatrix account https://yourcompanyname.quatrix.it/ (e.g. https://test-api.quatrix.it/). You can set up a free trial account [here](https://www.maytech.net/freetrial.html#trial=qtrx). Below you'll find information on how to authenticate in a Quatrix session, how to construct JSON formatted API call and what JSON responses to expect.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SearchQuery'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SearchQuery'));
  } else {
    // Browser globals (root is window)
    if (!root.QuatrixApi) {
      root.QuatrixApi = {};
    }
    root.QuatrixApi.SearchReq = factory(root.QuatrixApi.ApiClient, root.QuatrixApi.SearchQuery);
  }
}(this, function(ApiClient, SearchQuery) {
  'use strict';




  /**
   * The SearchReq model module.
   * @module model/SearchReq
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SearchReq</code>.
   * @alias module:model/SearchReq
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SearchReq</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchReq} obj Optional instance to populate.
   * @return {module:model/SearchReq} The populated <code>SearchReq</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_and')) {
        obj['_and'] = ApiClient.convertToType(data['_and'], [SearchQuery]);
      }
      if (data.hasOwnProperty('_or')) {
        obj['_or'] = ApiClient.convertToType(data['_or'], [SearchQuery]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/SearchQuery>} _and
   */
  exports.prototype['_and'] = undefined;
  /**
   * @member {Array.<module:model/SearchQuery>} _or
   */
  exports.prototype['_or'] = undefined;



  return exports;
}));


