/**
 * Quatrix API
 * The Quatrix API enables you to automate your interaction with Quatrix using any scripting or programming language. You can test API calls on [Swagger](https://docs.maytech.net/swagger/), the interactive environment we use as the repository for the Quatrix API. In order to authorize to Quatrix API you will need to have a Quatrix account https://yourcompanyname.quatrix.it/ (e.g. https://test-api.quatrix.it/). You can set up a free trial account [here](https://www.maytech.net/freetrial.html#trial=qtrx). Below you'll find information on how to authenticate in a Quatrix session, how to construct JSON formatted API call and what JSON responses to expect.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AutomationCreateReq', 'model/AutomationDeleteResp', 'model/AutomationEditReq', 'model/AutomationResp', 'model/ErrorModel', 'model/IdsReq'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AutomationCreateReq'), require('../model/AutomationDeleteResp'), require('../model/AutomationEditReq'), require('../model/AutomationResp'), require('../model/ErrorModel'), require('../model/IdsReq'));
  } else {
    // Browser globals (root is window)
    if (!root.QuatrixApi) {
      root.QuatrixApi = {};
    }
    root.QuatrixApi.AutomationApi = factory(root.QuatrixApi.ApiClient, root.QuatrixApi.AutomationCreateReq, root.QuatrixApi.AutomationDeleteResp, root.QuatrixApi.AutomationEditReq, root.QuatrixApi.AutomationResp, root.QuatrixApi.ErrorModel, root.QuatrixApi.IdsReq);
  }
}(this, function(ApiClient, AutomationCreateReq, AutomationDeleteResp, AutomationEditReq, AutomationResp, ErrorModel, IdsReq) {
  'use strict';

  /**
   * Automation service.
   * @module api/AutomationApi
   * @version 1.0.0
   */

  /**
   * Constructs a new AutomationApi. 
   * @alias module:api/AutomationApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the automationCreatePost operation.
     * @callback module:api/AutomationApi~automationCreatePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AutomationResp} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create automation
     * Create new automation 
     * @param {module:model/AutomationCreateReq} body 
     * @param {module:api/AutomationApi~automationCreatePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AutomationResp}
     */
    this.automationCreatePost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling automationCreatePost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = AutomationResp;

      return this.apiClient.callApi(
        '/automation/create', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the automationDeletePost operation.
     * @callback module:api/AutomationApi~automationDeletePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AutomationDeleteResp} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete automations
     * Delete automations 
     * @param {module:model/IdsReq} body 
     * @param {module:api/AutomationApi~automationDeletePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AutomationDeleteResp}
     */
    this.automationDeletePost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling automationDeletePost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = AutomationDeleteResp;

      return this.apiClient.callApi(
        '/automation/delete', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the automationEditPost operation.
     * @callback module:api/AutomationApi~automationEditPostCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AutomationResp>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edit automation
     * Edit automation 
     * @param {module:model/AutomationEditReq} body 
     * @param {module:api/AutomationApi~automationEditPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AutomationResp>}
     */
    this.automationEditPost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling automationEditPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [AutomationResp];

      return this.apiClient.callApi(
        '/automation/edit/', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the automationGet operation.
     * @callback module:api/AutomationApi~automationGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AutomationResp>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List automations
     * List of all automations 
     * @param {module:api/AutomationApi~automationGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AutomationResp>}
     */
    this.automationGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [AutomationResp];

      return this.apiClient.callApi(
        '/automation', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the automationMetadataIdGet operation.
     * @callback module:api/AutomationApi~automationMetadataIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AutomationResp} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Automation metadata
     * Get automation metadata 
     * @param {String} id ID of an automation
     * @param {module:api/AutomationApi~automationMetadataIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AutomationResp}
     */
    this.automationMetadataIdGet = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling automationMetadataIdGet");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = AutomationResp;

      return this.apiClient.callApi(
        '/automation/metadata/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
