/**
 * Quatrix API
 * The Quatrix API enables you to automate your interaction with Quatrix using any scripting or programming language. You can test API calls on [Swagger](https://docs.maytech.net/swagger/), the interactive environment we use as the repository for the Quatrix API. In order to authorize to Quatrix API you will need to have a Quatrix account https://yourcompanyname.quatrix.it/ (e.g. https://test-api.quatrix.it/). You can set up a free trial account [here](https://www.maytech.net/freetrial.html#trial=qtrx). Below you'll find information on how to authenticate in a Quatrix session, how to construct JSON formatted API call and what JSON responses to expect.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorModel', 'model/SettingsAuthMethodsRespItems', 'model/SettingsResp', 'model/SettingsSetReq', 'model/SettingsUploadLogoLinkResp'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ErrorModel'), require('../model/SettingsAuthMethodsRespItems'), require('../model/SettingsResp'), require('../model/SettingsSetReq'), require('../model/SettingsUploadLogoLinkResp'));
  } else {
    // Browser globals (root is window)
    if (!root.QuatrixApi) {
      root.QuatrixApi = {};
    }
    root.QuatrixApi.SiteSettingsApi = factory(root.QuatrixApi.ApiClient, root.QuatrixApi.ErrorModel, root.QuatrixApi.SettingsAuthMethodsRespItems, root.QuatrixApi.SettingsResp, root.QuatrixApi.SettingsSetReq, root.QuatrixApi.SettingsUploadLogoLinkResp);
  }
}(this, function(ApiClient, ErrorModel, SettingsAuthMethodsRespItems, SettingsResp, SettingsSetReq, SettingsUploadLogoLinkResp) {
  'use strict';

  /**
   * SiteSettings service.
   * @module api/SiteSettingsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new SiteSettingsApi. 
   * @alias module:api/SiteSettingsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the settingsAuthMethodsGet operation.
     * @callback module:api/SiteSettingsApi~settingsAuthMethodsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/SettingsAuthMethodsRespItems>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get account auth-methods settings
     * Get account auth-methods settings 
     * @param {module:api/SiteSettingsApi~settingsAuthMethodsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/SettingsAuthMethodsRespItems>}
     */
    this.settingsAuthMethodsGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [SettingsAuthMethodsRespItems];

      return this.apiClient.callApi(
        '/settings/auth-methods', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the settingsGet operation.
     * @callback module:api/SiteSettingsApi~settingsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SettingsResp} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get site settings
     * Get site settings 
     * @param {module:api/SiteSettingsApi~settingsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SettingsResp}
     */
    this.settingsGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SettingsResp;

      return this.apiClient.callApi(
        '/settings', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the settingsSetPost operation.
     * @callback module:api/SiteSettingsApi~settingsSetPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SettingsResp} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Set site settings
     * Set site settings 
     * @param {module:model/SettingsSetReq} body 
     * @param {module:api/SiteSettingsApi~settingsSetPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SettingsResp}
     */
    this.settingsSetPost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling settingsSetPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SettingsResp;

      return this.apiClient.callApi(
        '/settings/set', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the settingsUploadLogoLinkGet operation.
     * @callback module:api/SiteSettingsApi~settingsUploadLogoLinkGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SettingsUploadLogoLinkResp} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get logo upload link
     * Get account logo upload link 
     * @param {module:api/SiteSettingsApi~settingsUploadLogoLinkGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SettingsUploadLogoLinkResp}
     */
    this.settingsUploadLogoLinkGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = SettingsUploadLogoLinkResp;

      return this.apiClient.callApi(
        '/settings/upload-logo-link', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
