/**
 * Quatrix API
 * Download and upload files or folders, share them with predefined security options, manage your account and profile settings and a lot more functionalities can be easily integrated into your application using our Quatrix APIs. Learn more how to authenticate the Quatrix session, how to construct JSON formatted API calls and what responses to expect in our [API Guide](https://docs.maytech.net/display/MD/API+Guide).
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QuatrixApi);
  }
}(this, function(expect, QuatrixApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QuatrixApi.ShareDownloadInfoResp();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ShareDownloadInfoResp', function() {
    it('should create an instance of ShareDownloadInfoResp', function() {
      expect(instance).to.be.a(QuatrixApi.ShareDownloadInfoResp);
    });

    it('should have the property id (base name: "id")', function() {
      expect(instance).to.have.property("id");
    });

    it('should have the property message (base name: "message")', function() {
      expect(instance).to.have.property("message");
    });

    it('should have the property subject (base name: "subject")', function() {
      expect(instance).to.have.property("subject");
    });

    it('should have the property activates (base name: "activates")', function() {
      expect(instance).to.have.property("activates");
    });

    it('should have the property expires (base name: "expires")', function() {
      expect(instance).to.have.property("expires");
    });

    it('should have the property senderName (base name: "sender_name")', function() {
      expect(instance).to.have.property("sender_name");
    });

    it('should have the property senderEmail (base name: "sender_email")', function() {
      expect(instance).to.have.property("sender_email");
    });

    it('should have the property userName (base name: "user_name")', function() {
      expect(instance).to.have.property("user_name");
    });

    it('should have the property userEmail (base name: "user_email")', function() {
      expect(instance).to.have.property("user_email");
    });

    it('should have the property locale (base name: "locale")', function() {
      expect(instance).to.have.property("locale");
    });

    it('should have the property userId (base name: "user_id")', function() {
      expect(instance).to.have.property("user_id");
    });

    it('should have the property pgpEncrypted (base name: "pgp_encrypted")', function() {
      expect(instance).to.have.property("pgp_encrypted");
    });

    it('should have the property privateKey (base name: "private_key")', function() {
      expect(instance).to.have.property("private_key");
    });

    it('should have the property pgpEnabled (base name: "pgp_enabled")', function() {
      expect(instance).to.have.property("pgp_enabled");
    });

    it('should have the property status (base name: "status")', function() {
      expect(instance).to.have.property("status");
    });

    it('should have the property shareType (base name: "share_type")', function() {
      expect(instance).to.have.property("share_type");
    });

    it('should have the property title (base name: "title")', function() {
      expect(instance).to.have.property("title");
    });

    it('should have the property expired (base name: "expired")', function() {
      expect(instance).to.have.property("expired");
    });

    it('should have the property isReply (base name: "is_reply")', function() {
      expect(instance).to.have.property("is_reply");
    });

    it('should have the property pinProtected (base name: "pin_protected")', function() {
      expect(instance).to.have.property("pin_protected");
    });

  });

}));
