/**
 * Quatrix API
 * Download and upload files or folders, share them with predefined security options, manage your account and profile settings and a lot more functionalities can be easily integrated into your application using our Quatrix APIs. Learn more how to authenticate the Quatrix session, how to construct JSON formatted API calls and what responses to expect in our [API Guide](https://docs.maytech.net/display/MD/Quatrix+API).
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QuatrixApi);
  }
}(this, function(expect, QuatrixApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QuatrixApi.TrackingCSVRespItems();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TrackingCSVRespItems', function() {
    it('should create an instance of TrackingCSVRespItems', function() {
      expect(instance).to.be.a(QuatrixApi.TrackingCSVRespItems);
    });

    it('should have the property time (base name: "Time")', function() {
      expect(instance).to.have.property("Time");
    });

    it('should have the property event (base name: "Event")', function() {
      expect(instance).to.have.property("Event");
    });

    it('should have the property action (base name: "Action")', function() {
      expect(instance).to.have.property("Action");
    });

    it('should have the property clientIPs (base name: "Client IPs")', function() {
      expect(instance).to.have.property("Client IPs");
    });

    it('should have the property userName (base name: "User name")', function() {
      expect(instance).to.have.property("User name");
    });

    it('should have the property email (base name: "Email")', function() {
      expect(instance).to.have.property("Email");
    });

    it('should have the property userStatus (base name: "User status")', function() {
      expect(instance).to.have.property("User status");
    });

    it('should have the property protocol (base name: "Protocol")', function() {
      expect(instance).to.have.property("Protocol");
    });

    it('should have the property payload (base name: "Payload")', function() {
      expect(instance).to.have.property("Payload");
    });

  });

}));
