/**
 * Quatrix API
 * The Quatrix API enables you to automate your interaction with Quatrix using any scripting or programming language. You can test API calls on [Swagger](https://docs.maytech.net/swagger/), the interactive environment we use as the repository for the Quatrix API. In order to authorize to Quatrix API you will need to have a Quatrix account https://yourcompanyname.quatrix.it/ (e.g. https://test-api.quatrix.it/). You can set up a free trial account [here](https://www.maytech.net/freetrial.html#trial=qtrx). Below you'll find information on how to authenticate in a Quatrix session, how to construct JSON formatted API call and what JSON responses to expect.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QuatrixApi);
  }
}(this, function(expect, QuatrixApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QuatrixApi.TrackingCSVRespItems();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TrackingCSVRespItems', function() {
    it('should create an instance of TrackingCSVRespItems', function() {
      // uncomment below and update the code to test TrackingCSVRespItems
      //var instane = new QuatrixApi.TrackingCSVRespItems();
      //expect(instance).to.be.a(QuatrixApi.TrackingCSVRespItems);
    });

    it('should have the property time (base name: "Time")', function() {
      // uncomment below and update the code to test the property time
      //var instane = new QuatrixApi.TrackingCSVRespItems();
      //expect(instance).to.be();
    });

    it('should have the property event (base name: "Event")', function() {
      // uncomment below and update the code to test the property event
      //var instane = new QuatrixApi.TrackingCSVRespItems();
      //expect(instance).to.be();
    });

    it('should have the property action (base name: "Action")', function() {
      // uncomment below and update the code to test the property action
      //var instane = new QuatrixApi.TrackingCSVRespItems();
      //expect(instance).to.be();
    });

    it('should have the property clientIPs (base name: "Client IPs")', function() {
      // uncomment below and update the code to test the property clientIPs
      //var instane = new QuatrixApi.TrackingCSVRespItems();
      //expect(instance).to.be();
    });

    it('should have the property userName (base name: "User name")', function() {
      // uncomment below and update the code to test the property userName
      //var instane = new QuatrixApi.TrackingCSVRespItems();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "Email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new QuatrixApi.TrackingCSVRespItems();
      //expect(instance).to.be();
    });

    it('should have the property userStatus (base name: "User status")', function() {
      // uncomment below and update the code to test the property userStatus
      //var instane = new QuatrixApi.TrackingCSVRespItems();
      //expect(instance).to.be();
    });

    it('should have the property protocol (base name: "Protocol")', function() {
      // uncomment below and update the code to test the property protocol
      //var instane = new QuatrixApi.TrackingCSVRespItems();
      //expect(instance).to.be();
    });

    it('should have the property payload (base name: "Payload")', function() {
      // uncomment below and update the code to test the property payload
      //var instane = new QuatrixApi.TrackingCSVRespItems();
      //expect(instance).to.be();
    });

  });

}));
