/**
 * Quatrix API
 * The Quatrix API enables you to automate your interaction with Quatrix using any scripting or programming language. You can test API calls on [Swagger](https://docs.maytech.net/swagger/), the interactive environment we use as the repository for the Quatrix API. In order to authorize to Quatrix API you will need to have a Quatrix account https://yourcompanyname.quatrix.it/ (e.g. https://test-api.quatrix.it/). You can set up a free trial account [here](https://www.maytech.net/freetrial.html#trial=qtrx). Below you'll find information on how to authenticate in a Quatrix session, how to construct JSON formatted API call and what JSON responses to expect.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QuatrixApi);
  }
}(this, function(expect, QuatrixApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QuatrixApi.UserResp();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserResp', function() {
    it('should create an instance of UserResp', function() {
      // uncomment below and update the code to test UserResp
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be.a(QuatrixApi.UserResp);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property parentId (base name: "parent_id")', function() {
      // uncomment below and update the code to test the property parentId
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property homeId (base name: "home_id")', function() {
      // uncomment below and update the code to test the property homeId
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property homeName (base name: "home_name")', function() {
      // uncomment below and update the code to test the property homeName
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property superAdmin (base name: "super_admin")', function() {
      // uncomment below and update the code to test the property superAdmin
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property quota (base name: "quota")', function() {
      // uncomment below and update the code to test the property quota
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property created (base name: "created")', function() {
      // uncomment below and update the code to test the property created
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property modified (base name: "modified")', function() {
      // uncomment below and update the code to test the property modified
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property groups (base name: "groups")', function() {
      // uncomment below and update the code to test the property groups
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property userOperations (base name: "user_operations")', function() {
      // uncomment below and update the code to test the property userOperations
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property effectiveOperations (base name: "effective_operations")', function() {
      // uncomment below and update the code to test the property effectiveOperations
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property homeOperations (base name: "home_operations")', function() {
      // uncomment below and update the code to test the property homeOperations
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property language (base name: "language")', function() {
      // uncomment below and update the code to test the property language
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property storageId (base name: "storage_id")', function() {
      // uncomment below and update the code to test the property storageId
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property hasKey (base name: "has_key")', function() {
      // uncomment below and update the code to test the property hasKey
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property services (base name: "services")', function() {
      // uncomment below and update the code to test the property services
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property uniqueLogin (base name: "unique_login")', function() {
      // uncomment below and update the code to test the property uniqueLogin
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property customSftpHome (base name: "custom_sftp_home")', function() {
      // uncomment below and update the code to test the property customSftpHome
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property sftpHome (base name: "sftp_home")', function() {
      // uncomment below and update the code to test the property sftpHome
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property readonly (base name: "readonly")', function() {
      // uncomment below and update the code to test the property readonly
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property authMethods (base name: "auth_methods")', function() {
      // uncomment below and update the code to test the property authMethods
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property lastLogin (base name: "last_login")', function() {
      // uncomment below and update the code to test the property lastLogin
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property storageUsed (base name: "storage_used")', function() {
      // uncomment below and update the code to test the property storageUsed
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

    it('should have the property forcedAuth (base name: "forced_auth")', function() {
      // uncomment below and update the code to test the property forcedAuth
      //var instane = new QuatrixApi.UserResp();
      //expect(instance).to.be();
    });

  });

}));
