/**
 * Quatrix API
 * Download and upload files or folders, share them with predefined security options, manage your account and profile settings and a lot more functionalities can be easily integrated into your application using our Quatrix APIs. Learn more how to authenticate the Quatrix session, how to construct JSON formatted API calls and what responses to expect in our [API Guide](https://docs.maytech.net/display/MD/Quatrix+API).
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QuatrixApi);
  }
}(this, function(expect, QuatrixApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QuatrixApi.SSHKeyApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SSHKeyApi', function() {
    describe('sshKeyCreatePost', function() {
      it('should call sshKeyCreatePost successfully', function(done) {
        //uncomment below and update the code to test sshKeyCreatePost
        //instance.sshKeyCreatePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sshKeyDeletePost', function() {
      it('should call sshKeyDeletePost successfully', function(done) {
        //uncomment below and update the code to test sshKeyDeletePost
        //instance.sshKeyDeletePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sshKeyEditPost', function() {
      it('should call sshKeyEditPost successfully', function(done) {
        //uncomment below and update the code to test sshKeyEditPost
        //instance.sshKeyEditPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sshKeyGet', function() {
      it('should call sshKeyGet successfully', function(done) {
        //uncomment below and update the code to test sshKeyGet
        //instance.sshKeyGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sshKeyIdGet', function() {
      it('should call sshKeyIdGet successfully', function(done) {
        //uncomment below and update the code to test sshKeyIdGet
        //instance.sshKeyIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sshKeyMetadataIdGet', function() {
      it('should call sshKeyMetadataIdGet successfully', function(done) {
        //uncomment below and update the code to test sshKeyMetadataIdGet
        //instance.sshKeyMetadataIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
